export const resources = {
  en: {
    translation: {
      "Select Language": "Select Language",
      "Donate": "DONATE",
      "Our Organizations": "Our Organizations",
      "Advancing Justice": "Advancing Justice",
      "Asian Law Caucus": "Asian Law Caucus",
      "Atlanta": "Atlanta",
      "Chicago": "Chicago",
      "Los Angeles": "Los Angeles",
      "Donate Today": "DONATE TODAY",
      "AAAJ": "Asian Americans Advancing Justice",
      "rights": "Some rights reserved",
      "Creative Commons": "All images used are licensed under the Creative Commons License.",
      "Learn More": "Please contact your local affiliate to learn more about our work.",
      
      "How AJ Helps": "HOW ADVANCING JUSTICE HELPS",
      "Leadership":"LEADERSHIP",
      "Leadership Desc": "We equip community members with strategies to combat anti-Asian hate and harassment.",
      "Support": "DIRECT SUPPORT",
      "Support Desc":"We equip community members with strategies to combat anti-Asian hate and harassment.",
      "Advocacy": "ADVOCACY",
      "Advocacy Desc":"We connect communities through our leadership in coalitions at the city, state, and national levels.",
      "Training": "BYSTANDER INTERVENTION TRAININGS",
      "Training Desc":"We equip community members with strategies to combat anti-Asian hate and harassment.",
      "Engagement":"CIVIC ENGAGEMENT",
      "Engagement Desc":"We grow power and mobilize for racial equity year round through our civic engagement efforts.",
      "Immigration":"IMMIGRATION RIGHTS",
      "Immigration Desc":"Immigration continues to be a significant, current, life-affecting issue for AAPIs across the country.",
      "Stand Up": "Help stand up against hate",
      "Successes":"SUCCESSES"
    }
  },
  hi: {
    translation: {
      "Select Language": "भाषा का चयन करें",
      "Donate": "दान करना",
      "Our Organizations": "हमारे संगठन",
      "Advancing Justice": "न्याय को आगे बढ़ाना",
      "Asian Law Caucus": "एशियाई कानून काकस",
      "Atlanta": "अटलांटा",
      "Chicago": "शिकागो",
      "Los Angeles": "लॉस एंजिल्स",
      "Donate Today": "आज दान करें",
      "AAAJ": "एशियाई अमेरिकी न्याय को आगे बढ़ाते हुए",
      "Rights":"कुछ अधिकार सुरक्षित",
      "Creative Commons": "उपयोग की गई सभी छवियां क्रिएटिव कॉमन्स लाइसेंस के तहत लाइसेंस प्राप्त हैं।",
      "Learn More":"हमारे काम के बारे में अधिक जानने के लिए कृपया अपने स्थानीय सहयोगी से संपर्क करें।",

      "How AJ Helps": "न्याय कैसे आगे बढ़ाता है",
      "Leadership":"नेतृत्व",
      "Leadership Desc": "हम एशियाई विरोधी घृणा और उत्पीड़न का मुकाबला करने के लिए समुदाय के सदस्यों को रणनीतियों से लैस करते हैं।",
      "Support": "प्रत्यक्ष समर्थन",
      "Support Desc":"हम एशियाई विरोधी घृणा और उत्पीड़न का मुकाबला करने के लिए समुदाय के सदस्यों को रणनीतियों से लैस करते हैं।",
      "Advocacy": "वकालत",
      "Advocacy Desc":"हम शहर, राज्य और राष्ट्रीय स्तर पर गठबंधन में अपने नेतृत्व के माध्यम से समुदायों को जोड़ते हैं।",
      "Training": "अंतर प्रशिक्षण",
      "Training Desc":"हम एशियाई विरोधी घृणा और उत्पीड़न का मुकाबला करने के लिए समुदाय के सदस्यों को रणनीतियों से लैस करते हैं।",
      "Engagement":"सिविक सगाई",
      "Engagement Desc":"हम अपने नागरिक जुड़ाव प्रयासों के माध्यम से नस्लीय इक्विटी वर्ष दौर के लिए शक्ति बढ़ाते हैं और जुटाते हैं।",
      "Immigration":"इमेजिंग अधिकार",
      "Immigration Desc":"देश भर में एशियाई अमेरिकी और प्रशांत द्वीप समूह के लिए आव्रजन एक महत्वपूर्ण, वर्तमान, जीवन को प्रभावित करने वाला मुद्दा है।",
      "Stand Up": "नफरत के खिलाफ खड़े होने में मदद करें",
      "Successes":"सफलताओं"
    }
  },
  vi: {
    translation: {
      "Select Language": "Chọn ngôn ngữ",
      "Donate": "Quyên góp",
      "Our Organizations": "Tổ chức của chúng tôi",
      "Advancing Justice": "Nâng cao công lý",
      "Asian Law Caucus": "Cuộc họp kín về Luật Châu Á",
      "Atlanta": "Atlanta",
      "Chicago": "Chicago",
      "Los Angeles": "Los Angeles",
      "Donate Today": "Quyên góp ngay hôm nay",
      "AAAJ": "Người Mỹ gốc Á ủng hộ công lý",
      "Rights":"Một số quyền được bảo lưu",
      "Creative Commons": "Tất cả các hình ảnh được sử dụng đều được cấp phép theo Giấy phép Creative Commons.",
      "Learn More":"Vui lòng liên hệ với chi nhánh địa phương của bạn để tìm hiểu thêm về công việc của chúng tôi.",

      "How AJ Helps": "CÁCH NÂNG CAO CÔNG LÝ GIÚP",
      "Leadership":"KHẢ NĂNG LÃNH ĐẠO",
      "Leadership Desc": "Chúng tôi trang bị cho các thành viên cộng đồng các chiến lược để chống lại sự thù ghét và quấy rối chống người châu Á.",
      "Support": "",
      "Support Desc":"Chúng tôi trang bị cho các thành viên cộng đồng các chiến lược để chống lại sự thù ghét và quấy rối chống người châu Á.",
      "Advocacy": "chức trạng sư",
      "Advocacy Desc":"Chúng tôi kết nối các cộng đồng thông qua vai trò lãnh đạo của chúng tôi trong các liên minh ở cấp thành phố, tiểu bang và quốc gia.",
      "Training": "ĐÀO TẠO CAN THIỆP BẰNG NHAU",
      "Training Desc":"Chúng tôi trang bị cho các thành viên cộng đồng các chiến lược để chống lại sự thù ghét và quấy rối chống người châu Á.",
      "Engagement":"KẾT NỐI CỘNG ĐỒNG",
      "Engagement Desc":"Chúng tôi phát triển quyền lực và huy động cho sự bình đẳng chủng tộc quanh năm thông qua các nỗ lực gắn kết công dân của chúng tôi.",
      "Immigration":"QUYỀN DI TRÚ",
      "Immigration Desc":"Nhập cư tiếp tục là một vấn đề quan trọng, hiện tại, ảnh hưởng đến cuộc sống của người Mỹ gốc Á và các Đảo Thái Bình Dương trên khắp đất nước.",
      "Stand Up": "Giúp đứng lên chống lại sự căm ghét",
      "Successes":"THÀNH CÔNG"
    }
  },
  ur: {
    translation: {
      "Select Language": "زبان منتخب کریں",
      "Donate": "عطیہ کریں",
      "Our Organizations": "ہماری تنظیمیں",
      "Advancing Justice": "ایڈوانسنگ جسٹس",
      "Asian Law Caucus": "ایشی قانون قفقاز",
      "Atlanta": "اٹلانٹا",
      "Chicago": "شکاگو",
      "Los Angeles": "لاس اینجلس",
      "Donate Today": "آج عطیہ کریں",
      "AAAJ": "ایشیائی امریکی انصاف کی پیش کش کررہے ہیں",
      "Rights":"کچھ حقوق محفوظ ہیں",
      "Creative Commons": "استعمال شدہ تمام تصاویر تخلیقی العام لائسنس کے تحت لائسنس یافتہ ہیں۔",
      "Learn More":"ہمارے کام کے بارے میں مزید معلومات کے ل. مقامی وابستہ سے رابطہ کریں۔",

      "How AJ Helps": "کس طرح ایڈوانسائز جسٹس مدد",
      "Leadership":"لیڈرشپ",
      "Leadership Desc": "ہم کمیونٹی کے ممبروں کو ایشین مخالف نفرت اور ہراساں کرنے کے خلاف حکمت عملی سے لیس کرتے ہیں۔",
      "Support": "ڈائریکٹ سپورٹ",
      "Support Desc":"ہم کمیونٹی کے ممبروں کو ایشین مخالف نفرت اور ہراساں کرنے کے خلاف حکمت عملی سے لیس کرتے ہیں۔",
      "Advocacy": "ایڈووکیسی",
      "Advocacy Desc":"ہم شہر ، ریاست اور قومی سطح پر اتحاد کے ذریعہ برادریوں کو اپنی قیادت کے ذریعے مربوط کرتے ہیں۔",
      "Training": "بیسنڈر انٹر وینٹ ٹریننگ",
      "Training Desc":"ہم کمیونٹی کے ممبروں کو ایشین مخالف نفرت اور ہراساں کرنے کے خلاف حکمت عملی سے لیس کرتے ہیں۔",
      "Engagement":"شہری مشغولیت",
      "Engagement Desc":"ہم اپنی شہری شمولیت کی کوششوں کے ذریعہ سال بھر نسلی ایکویٹی کے لئے متحرک اور متحرک ہیں۔",
      "Immigration":"امیگریشن کے حقوق",
      "Immigration Desc":"ملک بھر میں ایشین امریکی اور بحر الکاہل کے جزیروں کے لئے امیگریشن ایک اہم ، حالیہ ، زندگی کو متاثر کرنے والا مسئلہ ہے۔",
      "Stand Up": "نفرت کے خلاف کھڑے ہونے میں مدد کریں",
      "Successes":"کامیابیاں",
    }
  },
  ko: {
    translation: {
      "Select Language": "언어 선택",
      "Donate": "기부",
      "Our Organizations": "우리 조직",
      "Advancing Justice": "정의 발전",
      "Asian Law Caucus": "아시아 법률 간부",
      "Atlanta": "애틀랜타",
      "Chicago": "시카고",
      "Los Angeles": "로스 앤젤레스",
      "Donate Today": "오늘 기부",
      "AAAJ": "정의를 발전시키는 아시아계 미국인",
      "rights": "일부 권리 보유",
      "Creative Commons": "사용 된 모든 이미지는 Creative Commons License에 따라 사용이 허가되었습니다.",
      "Learn More": "우리의 작업에 대해 자세히 알아 보려면 현지 제휴사에 문의하십시오.",
      
      "How AJ Helps": "정의의 발전이 어떻게 도움이 되는가",
      "Leadership":"지도",
      "Leadership Desc": "우리는 반 아시아 적 증오와 괴롭힘에 맞서 싸우기위한 전략을 지역 사회 구성원에게 제공합니다.",
      "Support": "직접 지원",
      "Support Desc":"우리는 반 아시아 적 증오와 괴롭힘에 맞서 싸우기위한 전략을 지역 사회 구성원에게 제공합니다.",
      "Advocacy": "옹호",
      "Advocacy Desc":"우리는 도시, 주 및 국가 차원에서 연합의 리더십을 통해 지역 사회를 연결합니다.",
      "Training": "증인 중재 훈련",
      "Training Desc":"우리는 반 아시아 적 증오와 괴롭힘에 맞서 싸우기위한 전략을 지역 사회 구성원에게 제공합니다.",
      "Engagement":"시민 참여",
      "Engagement Desc":"우리는 시민 참여 노력을 통해 연중 힘을 키우고 인종 평등을 위해 동원합니다.",
      "Immigration":"이민 권리",
      "Immigration Desc":"이민은 미국 전역의 아시아계 미국인 및 태평양 섬 주민들에게 계속해서 중요한 현재의 삶에 영향을 미치는 문제입니다.",
      "Stand Up": "증오에 맞설 수 있도록 도와주세요",
      "Successes":"성공"
    }
  },
};